"""Merge overlapping temporal chunks into a seamless frame sequence.

Generated by ``scripts/relight.py --long``, each chunk produces files named::

    {chunk_id:04d}.{frame_id:04d}.relit.png

This script blends the overlapping regions using normalised linear weights
so that each frame transitions smoothly between consecutive chunks.

Usage
-----
    python scripts/merge_chunks.py \\
        --input_dir  workspace/chunks/ \\
        --output_dir workspace/merged/ \\
        --t_batch_size  57 \\
        --overlap       32
"""

import argparse
import re
from collections import defaultdict
from pathlib import Path

import cv2
import numpy as np
from PIL import Image


# ---------------------------------------------------------------------------
# Filename helpers
# ---------------------------------------------------------------------------

def _parse_filename(name: str):
    """Return (chunk_id, frame_id, pass_type, ext) or None."""
    m = re.match(r'^(\d{4})\.(\d{4})\.([^.]+)\.(.+)$', name)
    if m:
        return int(m.group(1)), int(m.group(2)), m.group(3), m.group(4)
    return None


def _global_frame_id(chunk_id: int, frame_id: int, T: int, overlap: int) -> int:
    return chunk_id * (T - overlap) + frame_id


def _blend_weight(frame_id: int, T: int, overlap: int) -> float:
    """Linear ramp-up at the start, ramp-down at the end, plateau in the middle."""
    if frame_id < overlap:
        return frame_id / overlap
    if frame_id >= T - overlap:
        return 1.0 - (frame_id - (T - overlap)) / overlap
    return 1.0


# ---------------------------------------------------------------------------
# Image I/O
# ---------------------------------------------------------------------------

def _load(path: Path) -> np.ndarray:
    """Load image → float32 H×W×C in [0, 1]."""
    if path.suffix.lower() == '.exr':
        img = cv2.imread(str(path), cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
        if img is None:
            raise ValueError(f"Could not load EXR: {path}")
        return cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32)
    arr = np.array(Image.open(path)).astype(np.float32) / 255.0
    return arr


def _save(arr: np.ndarray, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.suffix.lower() == '.exr':
        cv2.imwrite(str(path), cv2.cvtColor(arr.astype(np.float32), cv2.COLOR_RGB2BGR))
    else:
        Image.fromarray((np.clip(arr, 0, 1) * 255).astype(np.uint8)).save(path)


# ---------------------------------------------------------------------------
# Core merge
# ---------------------------------------------------------------------------

def merge_chunks(input_dir: Path, output_dir: Path, T: int, overlap: int) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    step = T - overlap
    max_overlaps = (overlap + step - 1) // step + 1
    print(f"Step size: {step}  Max overlaps per frame: {max_overlaps}")

    # {pass_type: {global_frame_id: [(path, chunk_id, frame_id), ...]}}
    groups: dict = defaultdict(lambda: defaultdict(list))

    print("Scanning input files…")
    for p in input_dir.iterdir():
        if not p.is_file():
            continue
        parsed = _parse_filename(p.name)
        if parsed is None:
            continue
        chunk_id, frame_id, pass_type, _ = parsed
        gfid = _global_frame_id(chunk_id, frame_id, T, overlap)
        groups[pass_type][gfid].append((p, chunk_id, frame_id))

    print(f"Found {len(groups)} pass type(s): {sorted(groups)}")

    for pass_type in sorted(groups):
        print(f"\nProcessing '{pass_type}'…")
        global_frames = groups[pass_type]
        overlap_stats: dict = defaultdict(int)

        for gfid in sorted(global_frames):
            contributors = global_frames[gfid]
            n = len(contributors)
            overlap_stats[n] += 1

            if n == 1:
                src, _, _ = contributors[0]
                _save(_load(src), output_dir / f"{gfid:06d}.{pass_type}{src.suffix}")
            else:
                if overlap_stats[n] <= 3:
                    print(f"  Blending {n} chunks for global frame {gfid}")

                raw_weights = [
                    (_load(p), _blend_weight(fid, T, overlap), cid, fid)
                    for p, cid, fid in contributors
                ]
                total_raw = sum(w for _, w, _, _ in raw_weights) or 1.0

                blended: np.ndarray | None = None
                for img, rw, cid, fid in raw_weights:
                    nw = rw / total_raw
                    if overlap_stats[n] <= 2:
                        print(f"    chunk {cid} frame {fid}  raw={rw:.3f}  norm={nw:.3f}")
                    blended = img * nw if blended is None else blended + img * nw

                src = contributors[0][0]
                _save(blended, output_dir / f"{gfid:06d}.{pass_type}{src.suffix}")

        total = len(global_frames)
        print(f"  Completed '{pass_type}': {total} frames")
        for k in sorted(overlap_stats):
            print(f"    {overlap_stats[k]} frames with {k} overlapping chunk(s)")

    print(f"\nDone. Merged frames written to {output_dir}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Merge overlapping relight_video chunks")
    p.add_argument("--input_dir",   required=True, help="Output directory from relight.py --long")
    p.add_argument("--output_dir",  required=True, help="Destination for merged frames")
    p.add_argument("--t_batch_size",  type=int, default=57,
                   help="Frames per chunk used during relighting (default: 57)")
    p.add_argument("--overlap",       type=int, default=32,
                   help="Overlap used during relighting (default: 32)")
    return p.parse_args()


def main():
    args = parse_args()
    merge_chunks(
        Path(args.input_dir),
        Path(args.output_dir),
        T       = args.t_batch_size,
        overlap = args.overlap,
    )


if __name__ == "__main__":
    main()
